name = "week-13"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMzcwZWE1ZTMtOGI4Mi00OTdlLTgxMTgtZDNmOTFjMzhlN2E0IiwidGVuYW50X2lkIjoiNGVmMzUzOTlmYTIzMmIwMWZmOTgyODc5NTQwODQ1ZWRlODA2MTM1ZjVkODI4ZWUxOTE0NzQ5Yzg5MzMyZmYxMSIsImludGVybmFsX3NlY3JldCI6IjQ5OTgwZjlmLTUzNGEtNGFmNi1iMTk2LTllMGRiMWFkYWI0ZiJ9.aIuc42PZPJ0aZuYRJuv1M_au9fI0cxuR_7dAlMdRDn0"
JWT_SECRET = "secretpassword"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"